### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by aqeelat** [jazzband/django-auditlog#538]
```[tasklist]
### Tasks
- [ ] Sync docs with the release tags
- [ ] Make the latest released tag as the latest docs version
- [ ] Mark the master branch as the dev docs version
```

**Comment by hramezani** [comment]
Thanks @aqeelat for creating this issue.
Unfortunately, I am very busy these days. Do you have time to fix this problems? For sure I can help you.
Otherwise I will fix them someday

**Comment by aqeelat** [comment]
@jjkester can you please chime in here?

**Comment by huix11** [comment]
good

**Comment by hramezani** [comment]
@hugovk [updated the .readthedocs.yaml](https://github.com/jazzband/django-auditlog/commit/2bf675fcebb5299197aa29c0c842459c891e9e59) and now we have updated doc available in https://django-auditlog.readthedocs.io/en/latest/
